#+TITLE: Installing and configuring Arch Linux on Thinkpad X1 Carbon
#+DATE: <2016-06-04 Sat>
#+AUTHOR: Robert Kozikowski
#+EMAIL: r.kozikowski@gmail.com
* Introduction
I recently configured Arch Linux on the new Thinkpad X1 Carbon (4th generation) with dual booting to the pre-installed Windows 10 (for games I occasionally play).
[[https://raw.githubusercontent.com/kozikow/kozikow-blog/master/arch.org][This post was written in and is readable in the Emacs org mode format]].
* Prepare USB stick (on other computer with Ubuntu Linux 14.04)
** Download
Downloaded the =2016.06.01= image via torrent from https://www.archlinux.org/download/.
** Upload it to the usb stick
Article: https://wiki.archlinux.org/index.php/USB_flash_installation_media
*** Find out the name of your USB drive with lsblk
#+BEGIN_SRC bash :results output 
  lsblk | grep media
#+END_SRC
*** Make sure that it is not mounted.
#+BEGIN_SRC bash :results output
  umount /dev/sdb1
#+END_SRC
*** Burn the image with dd
#+BEGIN_SRC bash :results output
  cd ~/Downloads
  sudo dd bs=4M if=archlinux-2016.06.01-dual.iso of=/dev/sdb && sync
#+END_SRC
*** Verify
Re-plug the usb and:
#+BEGIN_SRC bash :results output
  ls /media/kozikow/ARCH*
#+END_SRC

#+BEGIN_EXAMPLE
 arch EFI isolinux loader
#+END_EXAMPLE
* Prepare Windows 10 for dual booting
Dual boot with Windows wiki link: https://wiki.archlinux.org/index.php/Dual_boot_with_Windows
** Shrink the Windows partition from Windows
Even if partition resizing is also supported from Linux, I feel like it's safer to do it from Windows.
1. Press start button
2. Create and format hard disk partitions
3. Right click C:/ and "Shrink Volume"
*** Shrinking limitations
Windows only lets me to reclaim 233 gb out of 474 gb.
I tried defragmentation or cleaning up some unnecessary files with no luck.
I think it's not that bad, since I can mount the NTFS partition from arch.
Therefore, I can keep the most space hungry files like movies on this partition.
** Check that Windows boots into the UEFI/GPT mode
You can check it on Windows in System Information->BIOS mode
You may consider reading about [[https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface][UEFI]] and [[https://wiki.archlinux.org/index.php/GUID_Partition_Table][GPT]].
If we want to dual boot with the existing Windows we need to use UEFI for Arch as well.
** [[https://wiki.archlinux.org/index.php/Dual_boot_with_Windows#Fast_Start-Up][Disable Fast Startup]]
If you don't, Linux NTFS driver may damage the NTFS disk.
[[http://www.tenforums.com/tutorials/4189-fast-startup-turn-off-windows-10-a.html][Windows 10 instructions.]]
* Boot Arch Linux
** Disable secure boot
It prevents Arch from booting.
1. Restart computer
2. Press Enter
3. F1->Security->Secure Boot
4. Change to disabled
5. Save and restart
** Boot
1. Press Enter
2. F12
3. Choose usb stick
4. Arch
* Create the partition
** [[*Shrink the Windows partition from Windows][Shrink the Windows partition from Windows]]
** No swap
Since the laptop have 8 GB of RAM it's not necessary, and if I decide I need it I can always use a [[https://wiki.archlinux.org/index.php/swap#Swap_file][swap file]].
** Create partition for Arch with [[https://wiki.archlinux.org/index.php/Fdisk#GPT_.28gdisk.29][gdisk]]
I decided I'll go with a single Linux partition, since my movies and music will be stored on the Windows partition.
I used gdisk to create a new partition. gdisk is installed by default on the usb stick.
#+BEGIN_SRC bash 
  gdisk /dev/sda
#+END_SRC
*p* to list all partition tables. Based on this I found that my new partition should be placed between sectors 507793408 and 998166527.
*n* to create a new partition. All default options were reasonable.
*w* to save
*** Verify that the new partition is there
#+BEGIN_SRC bash :results output
  lsblk
#+END_SRC
* Format the partition with ext4
Since the laptop have the SSD, I was contemplating trying out the [[https://wiki.archlinux.org/index.php/F2FS][F2FS]].
It's only [[https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.4-FS-4-Way][slightly faster according to some benchmarks]], so I decided to go with the ext4, since it's more mature.
[[https://wiki.archlinux.org/index.php/Solid_State_Drives][You may also want to read an arch wiki about SSDs.]]
** Install ext4
#+BEGIN_SRC bash :results output
  lsblk /dev/sda
  mkfs.ext4 /dev/sda5
  mount /dev/sda5 /mnt
#+END_SRC
** TODO /boot partition
From [[https://wiki.archlinux.org/index.php/beginners'_guide#Format_the_file_systems_and_enable_swap][wiki]]:
If a new UEFI system partition has been created on a UEFI/GPT system, it must be formatted with a fat32 file system:
# mkfs.fat -F32 /dev/sdxY
/mnt/boot is also recommended for mounting the (formatted or already existing) EFI System Partition on a UEFI/GPT system. See EFISTUB and related articles for alternatives.
** TODO [[https://www.archlinux.org/packages/extra/x86_64/ntfs-3g/][ntfs-3g]]
Alternative to kernel ntfs implementation. Better supports SSDs.
** TODO [[https://wiki.archlinux.org/index.php/Solid_State_Drives#Apply_periodic_TRIM_via_fstrim][Apply trim]]
* Connect to internet
#+BEGIN_SRC bash
  iw dev
  wifi-menu -o wlp4s0
#+END_SRC
* Install
#+BEGIN_SRC bash :results output
  pacstrap -i /mnt base base-devel
#+END_SRC
* Boot Loader
After brief investigation, I decided that I prefer the [[https://wiki.archlinux.org/index.php/Systemd-boot][systemd-boot]] as an x86_64 [[https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface][UEFI]] bootloader.
* Additional links
** Thinkpad Carbon arch wiki entries
https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon
https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon_(Gen_2)
https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon_(Gen_3)

