#+BLOG: wordpress
#+POSTID: 704
#+OPTIONS: toc:3
#+DATE: [2016-07-01 Fri 18:54]
#+TITLE: Top pandas, numpy and scipy functions used in github repos
#+AUTHOR: Robert Kozikowski
#+EMAIL: r.kozikowski@gmail.com
* Introduction
Github recently introduced file contents query-able on Google BigQuery.
My first post with the general introduction about it: https://kozikow.wordpress.com/2016/06/29/top-emacs-packages-used-in-github-repos/ .

numpy, scipy and pandas are popular data analysis python packages.
They are quite big, so it may be hard to distinguish between functions you would use all the time and functions that you use once in a while.

Using the new github contents on big query I calculated the most popular numpy, scipy and pandas functions.
I have found a few functions that I should have been using that I have not been aware of.

I will be using pre-extracted data with python file contents from https://bigquery.cloud.google.com/dataset/fh-bigquery:github_extracts.

* Top pandas functions
Results are approximate and based on the heuristic assumption that people usually prefix python pandas functions by "pd." or "pandas.".

#+BEGIN_SRC sql :results output
  SELECT
    TOP(REGEXP_EXTRACT(line, r'[^a-zA-Z](?:pd|pandas)\.([^",\(\,\`) \':\[\]/={}]*)'),500) function,
    COUNT(*) c
  FROM (
    SELECT
      SPLIT(content, '\n') AS line,
    FROM
      [fh-bigquery:github_extracts.contents_py]
    WHERE
      content CONTAINS "import pandas"
    HAVING
      NOT LEFT(LTRIM(line),1)='#'
      AND REGEXP_MATCH(line, r'[^a-zA-Z](?:pd|pandas)\.') );
#+END_SRC

[[https://docs.google.com/spreadsheets/d/1tKksWEr9VdFMAET3Lamky5vxJVGx41EPL2bvmNQOqDk/edit?usp=sharing][Full results are in google docs.]]
Top 20 results:

| function            | count |
|---------------------+-------|
| DataFrame           | 47478 |
| Series              | 19124 |
| read_csv            | 17567 |
| concat              |  7456 |
| Timestamp           |  7029 |
| date_range          |  3233 |
| to_datetime         |  3176 |
| Index               |  2772 |
| merge               |  2642 |
| util.testing        |  1856 |
| read_table          |  1683 |
| DatetimeIndex       |  1629 |
| isnull              |  1459 |
| DataFrame.from_dict |  1455 |
| NaT                 |  1268 |
| compat              |  1100 |
| Categorical         |  1027 |
| read_pickle         |   970 |
| read_excel          |   946 |
| eval                |   933 |
* Top numpy functions
Results are again approximate and it's a simple string replace from the pandas version.

#+BEGIN_SRC sql :results output
  SELECT
    TOP(REGEXP_EXTRACT(line, r'[^a-zA-Z](?:np|numpy)\.([^",\(\,\`) \':\[\]/={}]*)'),500) function,
    COUNT(*) c
  FROM (
    SELECT
      SPLIT(content, '\n') AS line,
    FROM
      [fh-bigquery:github_extracts.contents_py]
    WHERE
      content CONTAINS "import numpy"
    HAVING
      NOT LEFT(LTRIM(line),1)='#'
      AND REGEXP_MATCH(line, r'[^a-zA-Z](?:np|numpy)\.') );
#+END_SRC

[[https://docs.google.com/spreadsheets/d/1vnLzxw18derkNrB2XWmsI7oO7xMzmFjkNAnZvCrz_4I/edit?usp=sharing][Full results in google docs]].
Top 20 results:

| function    |  count |
|-------------+--------|
| array       | 604263 |
| zeros       | 280579 |
| arange      | 158705 |
| dot         |  90422 |
| sum         |  85793 |
| asarray     |  82563 |
| ones        |  80998 |
| sqrt        |  77810 |
| ndarray     |  71141 |
| linspace    |  62970 |
| where       |  56778 |
| mean        |  56402 |
| empty       |  51718 |
| nan         |  46614 |
| abs         |  43168 |
| exp         |  42446 |
| all         |  38571 |
| allclose    |  37450 |
| dtype       |  36794 |
| concatenate |  36532 |
| float32     |  34060 |

* Top scipy functions
Results are again approximate and it's a simple string replace from the numpy version.

#+BEGIN_SRC sql :results output
  SELECT
    TOP(REGEXP_EXTRACT(line, r'[^a-zA-Z](?:sp|scipy)\.([^",\(\,\`) \':\[\]/={}]*)'),500) function,
    COUNT(*) c
  FROM (
    SELECT
      SPLIT(content, '\n') AS line,
    FROM
      [fh-bigquery:github_extracts.contents_py]
    WHERE
      content CONTAINS "import scipy"
    HAVING
      NOT LEFT(LTRIM(line),1)='#'
      AND REGEXP_MATCH(line, r'[^a-zA-Z](?:sp|scipy)\.') );
#+END_SRC

[[https://docs.google.com/spreadsheets/d/1ngTMdVsojx5MOaz-zF1TSQuTbMZBAmbxGefCkGBEVMM/edit?usp=sharing][Full results in google docs.]]
Top 20 results:
| function          | count |
|-------------------+-------|
| sparse            |  6500 |
| stats             |  5717 |
| array             |  3873 |
| io                |  3079 |
| linalg            |  3047 |
| optimize          |  2788 |
| csr_matrix        |  2541 |
| zeros             |  2502 |
| issparse          |  2309 |
| ndimage           |  2196 |
| interpolate       |  2022 |
| signal            |  1883 |
| special           |  1792 |
| io.loadmat        |  1501 |
| sparse.csr_matrix |  1305 |
| csc_matrix        |  1150 |
| misc              |  1135 |
| arange            |  1123 |
| dot               |  1121 |
| sqrt              |  1100 |
| sparse.linalg     |  1056 |

* Top Pandas Data Frame Functions 
Results are again approximate and based on the heuristic assumption that data frames are usually named with the suffix "df".
To filter out noise, only files containing "import pandas" and matching regexp ".*df\s=.*pandas" are included.

#+BEGIN_SRC sql :results output
  SELECT
    TOP(REGEXP_EXTRACT(line, r"df([a-zA-Z-_\.]+)"), 500) AS pandas_function,
    COUNT(*)
  FROM (
    SELECT
      SPLIT(content, '\n') AS line,
    FROM
      [fh-bigquery:github_extracts.contents_py]
    WHERE
      content CONTAINS "import pandas"
      and REGEXP_MATCH(content, r".*df\s=.*pandas") 
    HAVING
      line CONTAINS "df.")
  HAVING LENGTH(pandas_function) > 1;
#+END_SRC

[[https://docs.google.com/spreadsheets/d/1QiWBm9YI-5BhkdSxvOioKwWH924s5DePMZOJu6zt5EM/edit?usp=sharing][Full results are in google docs.]] Top 20 results:

| data_frame_function | count |
|---------------------+-------|
| .columns            |  1712 |
| .index              |   441 |
| .loc                |   352 |
| .to_csv             |   344 |
| .groupby            |   319 |
| .set_index          |   241 |
| .x                  |   226 |
| .values             |   208 |
| .drop               |   203 |
| .divisions          |   197 |
| .ix                 |   165 |
| .fillna             |   158 |
| .dropna             |   147 |
| .iterrows           |   123 |
| .append             |   120 |
| .iloc               |   119 |
| .shape              |   117 |
| .to_html            |    93 |
| .rename             |    93 |
| .sort               |    92 |
| .compute            |    92 |

* Attribution 
My first version was improved upon by Felipe and suggested [[https://kozikow.wordpress.com/2016/07/01/top-pandas-functions-used-in-github-repos/#comment-99][in the comment.]]
